/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    'service-categories': ServiceCategory;
    services: Service;
    industries: Industry;
    'team-members': TeamMember;
    'mega-menus': MegaMenu;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    'service-categories': ServiceCategoriesSelect<false> | ServiceCategoriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'mega-menus': MegaMenusSelect<false> | MegaMenusSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fr') | ('en' | 'fr')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
    'home-page': HomePage;
    'advisory-page': AdvisoryPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'advisory-page': AdvisoryPageSelect<false> | AdvisoryPageSelect<true>;
  };
  locale: 'en' | 'fr';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-categories".
 */
export interface ServiceCategory {
  id: number;
  /**
   * Category name (e.g., "Technology", "Corporate Finance")
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., "technology", "corporate-finance")
   */
  slug: string;
  /**
   * Optional description of this category
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL slug for the service page (e.g., technology-strategy)
   */
  slug: string;
  /**
   * Service category for grouping in navigation
   */
  category: number | ServiceCategory;
  /**
   * Brief description shown in navigation menus
   */
  shortDescription?: string | null;
  /**
   * Optional image for service pages
   */
  featuredImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  name: string;
  /**
   * URL slug for the industry page (e.g., fintech)
   */
  slug: string;
  /**
   * Optional image for industry pages
   */
  featuredImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  /**
   * URL slug/anchor (e.g., maxime, alexandre)
   */
  slug: string;
  /**
   * Job title/role (e.g., Co-founder)
   */
  role: string;
  /**
   * Short bio/description
   */
  bio?: string | null;
  image: number | Media;
  /**
   * Link to full profile page (e.g., /about#maxime)
   */
  href?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mega-menus".
 */
export interface MegaMenu {
  id: number;
  /**
   * Internal name for this mega menu (e.g., "Advisory Menu")
   */
  name: string;
  /**
   * Optional overview link shown at the top of the mega menu
   */
  overviewLink?: {
    /**
     * Label for the overview link
     */
    label?: string | null;
    /**
     * Optional section heading label. If not provided, no heading will be shown.
     */
    sectionLabel?: string | null;
    /**
     * URL path for the overview link
     */
    href?: string | null;
  };
  /**
   * Title displayed at the top of the Services column
   */
  servicesColumnTitle?: string | null;
  /**
   * URL path segment for services (e.g., "services"). Used to construct URLs like /basePath/{urlPathSegment}/{service-slug}. Defaults to "services" if not provided.
   */
  servicesUrlPathSegment?: string | null;
  /**
   * Service categories and their associated services to display in the mega menu
   */
  serviceCategories?:
    | {
        /**
         * Select the service category to display
         */
        category: number | ServiceCategory;
        /**
         * Select services to display in this category. Services will be filtered by the selected category automatically.
         */
        services: (number | Service)[];
        id?: string | null;
      }[]
    | null;
  /**
   * Title displayed at the top of the Industries column
   */
  industriesColumnTitle?: string | null;
  /**
   * Industries to display in the mega menu
   */
  industries?: (number | Industry)[] | null;
  /**
   * URL path segment for industries (e.g., "industries", "sectors"). Used to construct URLs like /basePath/{urlPathSegment}/{industry-slug}. Defaults to "items" if not provided.
   */
  industriesUrlPathSegment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'service-categories';
        value: number | ServiceCategory;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'mega-menus';
        value: number | MegaMenu;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-categories_select".
 */
export interface ServiceCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  shortDescription?: T;
  featuredImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  featuredImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  bio?: T;
  image?: T;
  href?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mega-menus_select".
 */
export interface MegaMenusSelect<T extends boolean = true> {
  name?: T;
  overviewLink?:
    | T
    | {
        label?: T;
        sectionLabel?: T;
        href?: T;
      };
  servicesColumnTitle?: T;
  servicesUrlPathSegment?: T;
  serviceCategories?:
    | T
    | {
        category?: T;
        services?: T;
        id?: T;
      };
  industriesColumnTitle?: T;
  industries?: T;
  industriesUrlPathSegment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site settings including company information and branding
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  company: {
    /**
     * Company name used throughout the site
     */
    name: string;
    /**
     * Full legal company name (e.g., "Aryes Advisory SA")
     */
    legalName?: string | null;
    /**
     * Primary contact email address
     */
    email: string;
    /**
     * Phone number (optional)
     */
    phone?: string | null;
    address: {
      street?: string | null;
      city: string;
      country: string;
      /**
       * Formatted address for display (e.g., "Geneva, Switzerland")
       */
      display: string;
    };
  };
  logo: {
    /**
     * Choose between text-based logo or image logo
     */
    type: 'text' | 'image';
    textLogo?: {
      /**
       * Text to display as logo
       */
      text: string;
      /**
       * Accent character/word after company name (e.g., ".")
       */
      accent?: string | null;
    };
    imageLogo?: {
      /**
       * Logo for light backgrounds
       */
      logoLight?: (number | null) | Media;
      /**
       * Logo for dark backgrounds (optional, falls back to light logo)
       */
      logoDark?: (number | null) | Media;
      alt?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure header navigation menu structure. Any navigation item can optionally have a mega menu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Define all navigation items. Each item can optionally have a mega menu.
   */
  items?:
    | {
        /**
         * Navigation label (e.g., "Advisory", "Capital", "About", "Contact")
         */
        label: string;
        /**
         * URL path (e.g., /advisory, /capital, /about, /contact)
         */
        href: string;
        /**
         * Select a mega menu to display for this navigation item (optional)
         */
        megaMenu?: (number | null) | MegaMenu;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure footer content and links
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Title for the Company column
   */
  companyColumnTitle: string;
  /**
   * Links shown in the Company column
   */
  companyLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Title for the Legal column
   */
  legalColumnTitle: string;
  /**
   * Links shown in the Legal column
   */
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Social media links (LinkedIn, etc.)
   */
  socialLinks?:
    | {
        platform: 'linkedin' | 'twitter' | 'other';
        /**
         * Full URL to the social media profile
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Title for the Language column
   */
  languageColumnTitle: string;
  /**
   * Copyright text. Use {year} for current year, {company} for company name, {location} for location.
   */
  copyright: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure home page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    /**
     * Main hero title
     */
    title: string;
    /**
     * Highlighted part of the title (e.g., "We build.")
     */
    titleHighlight: string;
    /**
     * Hero subtitle/description. Use bold text for highlighted parts.
     */
    subtitle: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Videos that rotate in the hero background
     */
    videos?:
      | {
          /**
           * Video file to display in the hero background
           */
          video: number | Media;
          id?: string | null;
        }[]
      | null;
    ctaButtons?:
      | {
          label: string;
          href: string;
          style?: ('secondary' | 'primary') | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Text displayed in the scroll indicator at the bottom of the hero section
     */
    scrollLabel: string;
  };
  whatWeDo: {
    /**
     * Add cards to display in the "What We Do" section
     */
    cards?:
      | {
          /**
           * Badge text shown at the top of the card (e.g., "Advisory", "Capital")
           */
          badge: string;
          /**
           * Card title
           */
          title: string;
          /**
           * Card description text
           */
          description: string;
          /**
           * Link URL (e.g., /advisory, /capital)
           */
          href: string;
          /**
           * Card background image
           */
          image: number | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Text displayed on the "Learn more" link in each card
     */
    learnMoreLabel: string;
  };
  approach: {
    label: string;
    title: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    description: string;
    ctaLabel: string;
    ctaHref: string;
    image: number | Media;
  };
  leadership: {
    label: string;
    title: string;
    description: string;
    /**
     * Select team members to display in the leadership section
     */
    teamMembers: (number | TeamMember)[];
  };
  contact: {
    title: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    description: string;
    /**
     * Contact email (references Site Settings company email by default)
     */
    email?: string | null;
    /**
     * Location display text (references Site Settings company address by default)
     */
    location?: string | null;
    ctaLabel: string;
    ctaHref: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure Advisory page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advisory-page".
 */
export interface AdvisoryPage {
  id: number;
  pageHeader: {
    /**
     * Category label shown above the title
     */
    category: string;
    /**
     * Main page title
     */
    title: string;
    /**
     * Subtitle/description text
     */
    subtitle: string;
    /**
     * Background image for the header
     */
    image: number | Media;
    /**
     * Show blue accent line below category
     */
    withBlueLine?: boolean | null;
    /**
     * Header size variant
     */
    size?: ('standard' | 'large') | null;
  };
  introSection: {
    title: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    description: string;
  };
  practiceAreas?:
    | {
        /**
         * Practice number label (e.g., "Practice 01", "Practice 02")
         */
        practiceNumber: string;
        title: string;
        description: string;
        image: number | Media;
        services?:
          | {
              label: string;
              /**
               * URL path (e.g., /advisory/services/technology-strategy)
               */
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  perspectiveSection: {
    label: string;
    title: string;
    quote: string;
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  industriesSection: {
    title: string;
    description: string;
    /**
     * Select industries to display in the industries section
     */
    industries: (number | Industry)[];
  };
  ctaSection: {
    /**
     * CTA title (supports rich text formatting)
     */
    title: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * CTA subtitle/description
     */
    subtitle: string;
    /**
     * Text displayed on the CTA button
     */
    buttonText: string;
    /**
     * URL path for the CTA button (e.g., /contact)
     */
    buttonLink: string;
    /**
     * Background color variant
     */
    backgroundColor?: ('stone' | 'white' | 'dark') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  company?:
    | T
    | {
        name?: T;
        legalName?: T;
        email?: T;
        phone?: T;
        address?:
          | T
          | {
              street?: T;
              city?: T;
              country?: T;
              display?: T;
            };
      };
  logo?:
    | T
    | {
        type?: T;
        textLogo?:
          | T
          | {
              text?: T;
              accent?: T;
            };
        imageLogo?:
          | T
          | {
              logoLight?: T;
              logoDark?: T;
              alt?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        megaMenu?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  companyColumnTitle?: T;
  companyLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  legalColumnTitle?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  languageColumnTitle?: T;
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        titleHighlight?: T;
        subtitle?: T;
        videos?:
          | T
          | {
              video?: T;
              id?: T;
            };
        ctaButtons?:
          | T
          | {
              label?: T;
              href?: T;
              style?: T;
              id?: T;
            };
        scrollLabel?: T;
      };
  whatWeDo?:
    | T
    | {
        cards?:
          | T
          | {
              badge?: T;
              title?: T;
              description?: T;
              href?: T;
              image?: T;
              id?: T;
            };
        learnMoreLabel?: T;
      };
  approach?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
        image?: T;
      };
  leadership?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
        teamMembers?: T;
      };
  contact?:
    | T
    | {
        title?: T;
        description?: T;
        email?: T;
        location?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advisory-page_select".
 */
export interface AdvisoryPageSelect<T extends boolean = true> {
  pageHeader?:
    | T
    | {
        category?: T;
        title?: T;
        subtitle?: T;
        image?: T;
        withBlueLine?: T;
        size?: T;
      };
  introSection?:
    | T
    | {
        title?: T;
        description?: T;
      };
  practiceAreas?:
    | T
    | {
        practiceNumber?: T;
        title?: T;
        description?: T;
        image?: T;
        services?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  perspectiveSection?:
    | T
    | {
        label?: T;
        title?: T;
        quote?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  industriesSection?:
    | T
    | {
        title?: T;
        description?: T;
        industries?: T;
      };
  ctaSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        buttonText?: T;
        buttonLink?: T;
        backgroundColor?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}